#model: yolov8m.pt           # 사용할 사전학습 모델
train_data_yaml: 'data.yaml'
test_image_dir: "data/raw/test_images"


# 학습 스케쥴
epochs: 20
patience: 15
image_size: 640 # [576, 960]
batch_size: 32

conf_threshold: 0.5
iou_threshold: 0.4