# TODO 테스트 이미지 들어있는 경로로 수정 필요
#model: yolov8n.pt           # 사용할 사전학습 모델

conf_threshold: 0.5
iou_threshold: 0.4

train_data_yaml: 'data.yaml'
test_image_dir: "data/raw/test_images"


epochs: 2
patience: 15
image_size: 416
batch_size: 32