paths:
  yolo_data_dir: data/yolo_split
  yolo_train_dir: data/yolo_split/train/images
  yolo_train_label: data/yolo_split/train/labels
  yolo_val_dir: data/yolo_split/val/images
  yolo_val_label: data/yolo_split/val/labels
  original_dataset: data/raw
  data_dir: data
  train_image_dir: data/raw/train_images
  train_annot_dir: data/raw/train_annotations
  data_yaml_path: config/data.yaml
  db_path: script/db/pill_metadata.db
  pickle_path: cache/parsed_dataset.pkl
  class_names_path: data/class_names.txt
