# config.yaml

# 모델·데이터
weights:       "yolo11n.pt"
data:          "data.yaml"

# 학습 스케줄
epochs:        50
batch:         16
imgsz:         640

# Optimizer 설정
optimizer:     "AdamW"      # ["SGD","Adam","AdamW"]
lr0:           0.01
lrf:           0.01
momentum:      0.937     # SGD 전용
betas:         [0.9,0.999] # Adam/AdamW 전용

# Data 경로 설정
test_images_dir: data/yolo_split/test/images

# 기타
weight_decay:  0.0005
warmup_epochs: 3
augment:       true      # or false
project:       "outputs/logs/yolo11"
name:          "exp"