# config.yaml

# 모델·데이터
weights:       "yolo11n.pt"
data:          "data.yaml"

# 학습 스케줄
epochs:        50
batch:         16
imgsz:         640

# 전이 학습 옵션
transfer_learning: false

# Optimizer 설정
optimizer:     "AdamW"      # ["SGD","Adam","AdamW"]
lr0:           0.01
lrf:           0.01
momentum:      0.937     # SGD 전용
warmup_epochs: 3
patience: 100

# Data 경로 설정
test_images_dir: data/yolo_split/test/images

# 기타
weight_decay:  0.0005
augment:       true      # or false
project:       "outputs/logs/yolo11"
name:          "exp"

# 추가
label_smoothing: 0.0
cos_lr: false
mixup: 0.0
degrees: 0.0
scale: 0.5
translate: 0.1
shear: 0.0