# -*- coding: utf-8 -*-
"""한번에 모든 브랜치 돌면서 커밋 받아오기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVFbOnoDuYUMhjvQOTqqNt93kwrjVMDd

##깃헙과 연결
"""

# 1) 환경 변수로 토큰 설정 (안전)
import os
os.environ['GITHUB_TOKEN'] = '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'

# 2) 토큰을 이용해 브랜치 전체 clone
!git clone https://$GITHUB_TOKEN@github.com/aisprint3team5/ai3-team5-pill-detection.git

# Commented out IPython magic to ensure Python compatibility.
###연결된 원격 브랜치 확인
# %cd /content/ai3-team5-pill-detection
!git fetch
!git branch -r
print("==========")
# 또는
!git ls-remote --heads origin

#현재 브랜치 확인
!git branch -a

!git branch

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# 
# # origin에 있는 모든 브랜치 목록 가져오기 (HEAD 제외)
# branches=$(git branch -r | grep origin/ | grep -v HEAD | sed 's# *origin/##')
# 
# for branch in $branches; do
#   echo "=== $branch 체크아웃 및 최신 커밋 업데이트 ==="
#   git fetch origin "$branch"
#   git checkout "$branch"
#   git pull --rebase origin "$branch"
# done
#

branch = "el/ETL"   # ← change this

##특정 브랜치에 체크아웃(연결)&최신 커밋받아오기
#%cd ai3-team5-pill-detection
!git fetch origin {branch}
!git checkout {branch}
!git pull --rebase origin {branch}

!git branch #다시 현재 연결된 브랜치 위치확인