name: venv_pill
channels:
  - defaults
dependencies:
  - python=3.13.5
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - pip
  - pip:
      - -r requirements_mac.txt